# Generated by Django 3.2.6 on 2021-08-07 05:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_members_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='registertime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
